server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
    name: springcloud-producers
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/zsf
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1809a?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html
mybatis:
  mapper-locations: classpath:mapper/*.xml




